name: mastermind_finals
description: "A new Flutter project."

# Prevents accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Defines version and build number for your application
version: 1.0.0+1

# Environment configuration for the Flutter SDK
environment:
  sdk: ^3.5.0

# Dependencies required for the project
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  riverpod: 2.5.1
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.2.1
  audioplayers: ^0.20.1
  audio_service: ^0.18.0
  just_audio: ^0.9.0  

# Dev dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true
  assets:
    - assets/audio/counter.mp3
    - assets/audio/up_down.mp3
    - assets/audio/win.mp3

  # Fonts used in the project
  fonts:
    - family: PixelifySans
      fonts:
        - asset: fonts/PixelifySans-Regular.ttf

  # To add assets, uncomment and modify this section as needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

# For more information on this file format, visit: https://dart.dev/tools/pub/pubspec
